;(set-background-color "black")
;(cua-mode 1)
(desktop-save-mode 1)                                      ;; save/restore opened files
(electric-pair-mode 1)
(global-auto-revert-mode 1)                                ;; when a file is updated outside emacs, make it update if it's already opened in emacs
(global-hl-line-mode 1)                                    ;; turn on highlighting current line
(global-linum-mode -1)                                      ;; show line numbers
(menu-bar-mode -1)
(scroll-bar-mode -1)
(set-face-attribute 'default nil :height 150)
(setq auto-window-vscroll nil)
(setq compilation-ask-about-save nil)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq visible-bell nil)
(setq ring-bell-function 'ignore)
(setq-default indent-tabs-mode -1)
(show-paren-mode 1)                                        ;; turn on bracket match highlight
(tool-bar-mode -1)
(tooltip-mode -1)
(setq tooltip-use-echo-area t)
(which-function-mode 1)
(fset 'yes-or-no-p 'y-or-n-p)
(setq next-line-add-newlines t)
(winner-mode 1)
(normal-erase-is-backspace-mode 0)
(setq column-number-mode t)
(savehist-mode 1)
(size-indication-mode t)
(set-language-environment "UTF-8")
(electric-indent-mode 1)
(setq scroll-conservatively 100)
(set-frame-font "Hack 15" nil t)
(setq create-lockfiles nil)
(setq compilation-auto-jump-to-first-error t)
(transient-mark-mode nil)
(setq compilation-always-kill t)
(setq tramp-default-method "ssh")
;(highlight-indentation-mode nil)
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
(defalias 'yes-or-no-p 'y-or-n-p)
(string-match "\\<XFT\\>" system-configuration-features)
