(define-key global-map (kbd "RET") 'newline-and-indent)
(global-set-key [delete] 'delete-char)
(global-set-key (kbd "<f1>") 'list-buffers)
(global-set-key (kbd "<f2>") 'helm-projectile-find-file)
(global-set-key (kbd "<f3>") 'helm-semantic-or-imenu)
(global-set-key (kbd "<f4>") 'bookmark-jump)
(global-set-key (kbd "<f5>") 'switch-to-term)
;(global-set-key (kbd "<f6>") 'switch-to-workflow)
(global-set-key (kbd "<f6>") 'avy-goto-word-1)
(global-set-key (kbd "<f9>") 'endless/compile-please) ;; This just compiles immediately.
(global-set-key (kbd "<f12>") 'open-next-line)
(global-set-key (kbd "M-<down>") 'move-text-down)
(global-set-key (kbd "M-<up>") 'move-text-up)
(global-set-key (kbd "M-/") 'hippie-expand)
(global-set-key (kbd "M-d") 'kill-word)
(global-set-key (kbd "M-g g") 'goto-line-show)
(global-set-key (kbd "M-g j") 'dumb-jump-go)
(global-set-key (kbd "M-g ,") 'dumb-jump-back)
(global-set-key (kbd "M-g q") 'dumb-jump-quick-look)
(global-set-key (kbd "M-j") (lambda () (interactive) (join-line -1)))
(global-set-key (kbd "M-o") 'ace-window)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-=") 'er/expand-region)
(global-set-key (kbd "C-=") 'er/mark-symbol)
(global-set-key (kbd "C-M-d") 'kill-whole-word)
(global-set-key (kbd "C-<f9>") 'compile) ;; This gives a regular `compile-command' prompt.
(global-set-key (kbd "C-0") 'delete-window-balance)
(global-set-key (kbd "C-1") 'delete-other-windows)
(global-set-key (kbd "C-2") 'split-window-below-focus)
(global-set-key (kbd "C-3") 'split-window-right-focus)
(global-set-key (kbd "C-,") 'xah-pop-local-mark-ring)
(global-set-key (kbd "C-<") 'pop-global-mark)
(global-set-key (kbd "C-.") 'helm-imenu-anywhere)
(global-set-key (kbd "C-S-f") 'helm-projectile-ag)
;(global-set-key (kbd "<C-return>" 'open-line-below)
;(global-set-key (kbd "<C-S-RET>") 'open-line-above)
(global-set-key (kbd "C-<f1>") 'toggle-narrow-exand)
(global-set-key (kbd "C-<f3>") 'helm-gtags-select)
(global-set-key (kbd "C-<up>") (lambda ()
                                 (interactive)
                                 (ignore-errors (next-line -5))))
(global-set-key (kbd "C-<down>") (lambda ()
                                 (interactive)
                                 (ignore-errors (next-line 5))))
(global-set-key (kbd "C-0") 'delete-window)
(global-set-key (kbd "C-c f") 'iy-go-to-char)
(global-set-key (kbd "C-c h") 'helm-command-prefix)
(global-set-key (kbd "C-c l") 'recenter-top-bottom)
(define-key global-map (kbd "C-c o") 'iedit-mode)
(global-set-key (kbd "C-c @ @") 'hs-hide-all)
(global-set-key (kbd "C-c @ h") 'hs-hide-block)
(global-set-key (kbd "C-c @ s") 'hs-show-block)
(global-set-key (kbd "C-c @ SPC") 'hs-show-all)
(global-set-key (kbd "C-f") 'isearch-forward)
(global-set-key (kbd "C-l") 'copy-whole-line)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x s") 'save-all)
(global-set-key (kbd "C-x <down>") 'pop-global-mark)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x C-r") 'rename-current-buffer-file)
(global-set-key [remap forward-word] 'forward-to-word)
